Update serialization.md
ilyachch/django-rest-framework-rusdoc pull request #14
Opened 2020-10-12 08:41 UTC by degterevz

fixes

2020-10-12 09:18 UTC, rufatpro approved these changes

2020-10-17 18:37 UTC, ilyachch requested changes

2020-10-17 18:37 UTC, ilyachch commented on quick-start/serialization.md
> +snippet = Snippet(code='print "hello, world"\n')
если ниже сделано через `()`, то и тут надо так же, вероятно

2020-10-23 08:48 UTC, ilyachch commented
@degterevz Also, please update your local fork - I've made a big update

2021-08-05 11:51 UTC, ilyachch commented on quick-start/serialization.md
> +snippet = Snippet(code='print "hello, world"\n')
@degterevz

2023-02-10 15:11 UTC, ilyachch commented
https://github.com/ilyachch/django-rest-framework-rusdoc/pull/33

globally updated, changes are out of date

2023-02-10 15:11 UTC, closed without merging