correction of grammatical errors
ilyachch/django-rest-framework-rusdoc pull request #27
Opened 2021-07-27 13:01 UTC by TitovRoman

2021-07-28 07:46 UTC, ilyachch requested changes

2021-07-28 07:46 UTC, ilyachch commented on quick-start/serialization.md
> +Руководство достаточно подробное, так что если вы хотите только поверхностный обзор, воспользуйтесь руководством по [быстрому старту](https://github.com/ilyachch/django-rest-framework-rusdoc/blob/mas
лучше заменить на (../quick-start.md)

2021-08-05 11:38 UTC, ilyachch commented on quick-start/serialization.md
> +Руководство достаточно подробное, так что если вы хотите только поверхностный обзор, воспользуйтесь руководством по [быстрому старту](https://github.com/ilyachch/django-rest-framework-rusdoc/blob/mas
@TitovRoman

2021-08-05 11:48 UTC, ilyachch approved these changes

2021-08-05 11:49 UTC, merged

2021-08-05 11:51 UTC, TitovRoman commented on quick-start/serialization.md
> +Руководство достаточно подробное, так что если вы хотите только поверхностный обзор, воспользуйтесь руководством по [быстрому старту](https://github.com/ilyachch/django-rest-framework-rusdoc/blob/mas
Поправил. Извиняюсь за задержку, думал, что владелец тоже может поправить :)